name: Run Summary Bot

# on:
#   schedule:
#     cron:
#       # every day at 8pm, excluding weekends
#       - 0 20 * * 1,2,3,4,5

on:
  pull_request:
  push:
    tags:
    - '**'
    branches:
    - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.5"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run bot.py
      run: |
        python ./bot.py
      # use secret env DISCORD_WEBHOOK variable

