name: Run Summary Bot

on:
  schedule:
    # Every weekday at 8PM
    - cron: 0 20 * * 1,2,3,4,5
  # push:
  #   branches:
  #   - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.5"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run bot.py
      run: python ./bot.py

